In [1]:
import csv

In [2]:
with open('tr', 'rb') as csvfile:
    trainreader = csv.reader(csvfile, delimiter=',')
    print trainreader

In [3]:
trainreader

In [4]:
for row in trainreader:
    print row

ValueError: I/O operation on closed file

In [43]:
import numpy as np
trainF = open('train.csv','w')
evalF = open('eval.csv', 'w')
images = []
scores = []
choice = []
with open('labelmap.txt', 'rb') as csvfile:
    trainreader = csv.reader(csvfile, delimiter=',')
    for row in trainreader:
        choice.append(row[0])
        images.append(row[1])
        scores.append(row[2])
    bins = np.linspace(0, 1, 10,endpoint=False)
    digitized = np.digitize(scores, bins)
    result = zip(choice,images,digitized)
    resultSet = set(result)
    for item in resultSet:
        if item[0]=="train":
            trainF.write("./images/dataset/" + item[1] + "," + "%d"%(item[2]) + "\n")
        else:
            evalF.write("./images/dataset/" + item[1] + "," + "%d"%(item[2]) + "\n")
trainF.close()
evalF.close()
    

In [32]:
bins = np.linspace(0,1,num=10,retstep=True,endpoint=False)
bins

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]), 0.1)

In [18]:
import numpy as np
data = np.random.random(100)
bins = np.linspace(0, 1, 10)
digitized = np.digitize(data, bins)

In [19]:
digitized

array([9, 1, 8, 4, 7, 4, 7, 5, 5, 3, 1, 3, 9, 2, 8, 8, 4, 3, 9, 8, 8, 4,
       1, 1, 9, 4, 3, 9, 2, 4, 7, 9, 2, 6, 1, 1, 6, 5, 1, 1, 4, 6, 2, 3,
       5, 3, 7, 6, 4, 1, 2, 8, 3, 1, 6, 6, 3, 3, 6, 4, 3, 2, 6, 6, 7, 9,
       5, 8, 8, 9, 1, 5, 5, 6, 1, 5, 8, 8, 9, 1, 9, 5, 7, 7, 9, 1, 1, 1,
       7, 4, 8, 7, 6, 3, 6, 4, 5, 2, 9, 5], dtype=int64)

In [20]:
data

array([9.81270266e-01, 6.03432702e-02, 8.12491920e-01, 4.22613129e-01,
       7.41829919e-01, 3.33693295e-01, 7.59343248e-01, 4.73912866e-01,
       4.92489308e-01, 2.52437440e-01, 2.17985312e-02, 2.56701682e-01,
       8.93368578e-01, 1.34787125e-01, 8.19120593e-01, 8.35650455e-01,
       3.58738237e-01, 2.93764047e-01, 9.69912155e-01, 8.83939575e-01,
       8.71312882e-01, 3.63583639e-01, 5.51701463e-02, 7.98947310e-02,
       8.90928978e-01, 3.62788168e-01, 3.18367162e-01, 9.42660065e-01,
       2.17511302e-01, 3.36393446e-01, 7.10197503e-01, 8.97287828e-01,
       1.11256333e-01, 5.55938694e-01, 3.30371436e-02, 3.47916362e-03,
       5.94873747e-01, 5.09813277e-01, 1.03576671e-01, 3.51734016e-02,
       3.99445165e-01, 5.78393053e-01, 1.89947230e-01, 2.63289859e-01,
       5.15472045e-01, 2.85057509e-01, 6.75470111e-01, 6.61370844e-01,
       3.47016561e-01, 4.71864676e-04, 1.49539064e-01, 7.81653090e-01,
       3.01562572e-01, 9.78835572e-02, 6.34239305e-01, 6.55442164e-01,
      